fix:ensure len(state.src) equals to len(state.srcCharCode)
executablebooks/markdown-it-py pull request #108
Opened 2020-12-25 02:42 UTC by geebos

2020-12-25 12:40 UTC, hukkinj1 commented on markdown_it/rules_core/state_core.py
> +        self.srcCharCode = [ord(c) for c in src] if src is not None else []
```suggestion
    @property
    def src(self):
        return self._src

    @src.setter
    def src(self, value):
        self._src = value
        self.srcCharCode = [ord(c) for c in self.src] if self.src is not None else []
```

2020-12-25 12:41 UTC, hukkinj1 commented on markdown_it/rules_core/normalize.py
> +    state.set_src(string)
```suggestion
    state.src = string
```

2020-12-25 12:44 UTC, hukkinj1 reviewed
Nice! I made suggestions that use the `@property` decorator to keep API identical to JS markdown-it.

With those changes I believe we can also remove line 10 from the `__init__` that sets `self.srcCharCode`.

2020-12-25 12:57 UTC, hukkinj1 commented
Also, might make sense to add the `@property` to `StateBase` base class only, to get identical behavior in all `StateBase` subclasses.

2020-12-25 15:04 UTC, geebos commented
> Also, might make sense to add the `@property` to `StateBase` base class only, to get identical behavior in all `StateBase` subclasses.

Nice suggestions! I have added the `@property` to `StateBase`. In addition, I have added `srcCharCode` to `@property` to avoid assigning srcCharCode from outer codes.

2020-12-25 15:18 UTC, hukkinj1 requested changes
We should be able to remove the line
```python
self.srcCharCode = [ord(c) for c in src] if src is not None else []
```
in `StateInline.__init__`.

In `StateBlock.__init__` we can make the lines
```python
        self.src = src
        if srcCharCode is not None:
            self.srcCharCode = srcCharCode
        else:
            self.srcCharCode = [ord(c) for c in src] if src is not None else []
```
something like
```python
        if srcCharCode is not None:
            self._src = src
            self.srcCharCode = srcCharCode
        else:
            self.src = src
```

This will keep the (presumably) performance improvement in place.

2020-12-25 15:18 UTC, hukkinj1 commented on markdown_it/ruler.py
> +        return self._srcCharCode
```suggestion
```

I think we have to remove this property and keep `srcCharCode` writeable. We write it directly in `StateBlock.__init__`. It seems to me like a performance optimization, but @chrisjsewell knows better.

2020-12-26 10:55 UTC, hukkinj1 commented
Looking good @geebos ! Did you see this comment https://github.com/executablebooks/markdown-it-py/pull/108#pullrequestreview-558823485 . You think those two changes can be used here too?

2020-12-26 12:57 UTC, geebos commented
> Looking good @geebos ! Did you see this comment [#108 (review)](https://github.com/executablebooks/markdown-it-py/pull/108#pullrequestreview-558823485) . You think those two changes can be used here too?

Thanks for reminding. I have added a `set_underline_src` method in `StateBase`, because we cant set `_src` directly in `StateBlock`.

2020-12-26 14:41 UTC, hukkinj1 commented
> we cant set _src directly in StateBlock.

What makes you think so? I believe this should work just fine as long as there's only one preceding underscore (`_src`), not two (`__src`). In case it's mypy that's giving you trouble, you can type annotate `self._src` in `StateBase` after the class declaration like
```python
class StateBase:
    _src: str
```

2020-12-26 14:55 UTC, geebos commented
You are right. I confuse them.

2020-12-26 15:45 UTC, hukkinj1 commented
Nice, this looks very good to me!

2020-12-29 01:04 UTC, chrisjsewell commented
thanks!

2020-12-29 01:05 UTC, merged