Minor fix to import commands & save to file
executablebooks/markdown-it-py pull request #150
Opened 2021-03-27 21:59 UTC by firasm

Hello,

I was playing with this package and noticed that there are a couple of warning messages with the current important commands. 

Also one other suggestion is to add some code for people to export the html to a file if they happen to not be working in an interactive python session. Happy to remove this if it doesn't make sense for others.

2021-03-31 02:40 UTC, chrisjsewell requested changes
thanks @firasm, can you change the file writing code though

2021-03-31 02:40 UTC, chrisjsewell commented on README.md
> +#text_file.close()
This should either use:

```python
with open("output.html", "w") as handle:
   handle.write(html_text)
```

or probably better these days

```python
from pathlib import Path
Path("output.html").write_text(html_text)
```

2021-03-31 06:53 UTC, chrisjsewell commented on README.md
> +#text_file.close()
```suggestion
## To export the html to a file, uncomment the lines below:
# from pathlib import Path
# Path("output.html").write_text(html_text)
```

2021-03-31 06:53 UTC, chrisjsewell commented on README.md
> +#text_file.close()
actually I'll just change it

2021-03-31 06:57 UTC, merged

2021-04-01 06:12 UTC, firasm commented
Thanks! By the time I woke up today your suggested change was already done :-) 

Hard to unlearn how to write to files!

2021-04-01 06:13 UTC, chrisjsewell commented
Yeh I was too impatient lol