Add simple typographic replacements
executablebooks/markdown-it-py pull request #59
Opened 2020-10-19 18:40 UTC by tsutsu3

## Issue

#5 

## Summary

Implemented `replacements (Simple typographic replacements)` rule.

## Change

- Added a test to make sure that even a single capital letter is matched correctly.

2020-10-19 19:08 UTC, chrisjsewell requested changes
Awesome thanks! Just a minor nitpick

2020-10-19 19:08 UTC, chrisjsewell commented on markdown_it/rules_core/replacements.py
> +RARE_RE = r"\+-|\.\.|\?\?\?\?|!!!!|,,|--"
```suggestion
RARE_RE = re.compile(r"\+-|\.\.|\?\?\?\?|!!!!|,,|--")
```

It's a bit more performant to pre-compile, then use e.g. `RARE_RE.search`

2020-10-19 19:08 UTC, chrisjsewell commented on markdown_it/rules_core/replacements.py
> +SCOPED_ABBR_RE = r"\((c|tm|r|p)\)"
```suggestion
SCOPED_ABBR_RE = re.compile(r"\((c|tm|r|p)\)", flags=re.IGNORECASE)
```

same as above

2020-10-19 19:11 UTC, chrisjsewell commented
Also you can just `pip install pre-commit`, then `pre-commit run -all` to correctly format

2020-10-19 19:12 UTC, chrisjsewell commented on markdown_it/rules_core/replacements.py
> +from typing import List
```suggestion
from typing import List, Match
```

2020-10-19 19:12 UTC, chrisjsewell commented on markdown_it/rules_core/replacements.py
> +def replaceFn(match: re.Match):
```suggestion
def replaceFn(match: Match):
```

2020-10-20 06:11 UTC, tsutsu3 commented on markdown_it/rules_core/replacements.py
> +from typing import List
Thank you.

I was just in trouble.

2020-10-20 09:36 UTC, tsutsu3 commented
If I add this line to `conf.py`:

`nitpick_ignore = [("py:class", "Match")]`

sphinx warning goes away, is it ok to add it?

How can I get rid of the warning?

2020-10-20 09:39 UTC, chrisjsewell commented
> sphinx warning goes away, is it ok to add it?

yep thats absolutely fine, I don't think there is another "fix"

2020-10-20 09:50 UTC, tsutsu3 commented
> > sphinx warning goes away, is it ok to add it?
> 
> yep thats absolutely fine, I don't think there is another "fix"

2020-10-20 10:45 UTC, tsutsu3 commented
I added `nitpick_ignore = [("py:class", "Match")]` in `conf.py`.

With python 3.7 there is no warning, but with python 3.6 the warning is still there.

```
/home/circleci/.local/lib/python3.6/site-packages/markdown_it/rules_core/replacements.py:docstring of markdown_it.rules_core.replacements.replaceFn:: WARNING: py:class reference target not found: Match[~ AnyStr]
generating indices...  genindex py-modindexdone
```

Hmm..., it's going to take some time to fix... 🤔 😕

2020-10-20 23:58 UTC, chrisjsewell commented
looking good to me 👍 Is it ready for review?

2020-10-21 00:10 UTC, tsutsu3 commented
Should I put together a commit with a rebase?

2020-10-21 00:11 UTC, chrisjsewell approved these changes

2020-10-21 00:13 UTC, chrisjsewell commented
yeh weird, it normally has the button here to update the branch

if you could rebase then thanks

2020-10-21 00:34 UTC, tsutsu3 commented
I checked "Allow edits by maintainers"

My pc env has changed. 😢 

I can't rebase, can you handle it for me? 🙏

2020-10-21 00:37 UTC, chrisjsewell commented
sorted thanks @tsutsu3 😄

2020-10-21 00:38 UTC, merged