Fix parsing of unicode codepoints larger than 0xFFFF
executablebooks/markdown-it-py pull request #81
Opened 2020-11-23 22:04 UTC by hukkinj1

Closes https://github.com/executablebooks/markdown-it-py/issues/80

This seems like a porting issue to me: Javascript needs two string characters for codepoints larger than `0xFFFF` but Python 3 can represent any unicode codepoint in one character.

This PR removes the handling that splits a large codepoint to two chars.

2020-11-24 00:32 UTC, hukkinj1 commented
@chrisjsewell can you think of any other places in the codebase where this Javascript string (string of UTF-16 code units) versus Python3 string (string of Unicode codepoints) difference could cause issues.

I just realized we unintentionally fixed one instance of this in https://github.com/executablebooks/markdown-it-py/pull/70 :smile: The old entity data seemed to contain UTF-16 code units.

2020-11-25 18:56 UTC, chrisjsewell commented
Not that I know of, I'll have a quick look later

2020-12-09 02:33 UTC, lesteve commented
Just a gentle reminder about this one ;-). I completely understand if you have higher priorities of course.

2020-12-13 11:14 UTC, chrisjsewell requested changes

2020-12-13 11:19 UTC, chrisjsewell commented on markdown_it/common/utils.py
> +def fromCodePoint(c: int) -> str:
```suggestion
def fromCodePoint(c: int) -> str:
   """Convert ordinal to unicode.
   
   Note, in the original Javascript two string characters were required,
   for codepoints larger than `0xFFFF`.
   But Python 3 can represent any unicode codepoint in one character.
   """
```

2020-12-13 11:20 UTC, chrisjsewell commented on markdown_it/common/utils.py
>      return chr(c)
```suggestion
    """Convert ordinal to unicode.

    Note, in the original Javascript two string characters were required,
    for codepoints larger than `0xFFFF`.
    But Python 3 can represent any unicode codepoint in one character.
    """
    return chr(c)
```

2020-12-13 11:22 UTC, chrisjsewell approved these changes

2020-12-13 11:22 UTC, merged